/*******************************************************************************
 *                                                                             *
 * Project:      Filtering DNS Resolver                                        *
 * University:   Faculty of Information Technology, BUT                        *
 * Subject:      ISA: Network Applications and Network Administration          *
 *                                                                             *
 * File:         CommandLineOptions.hpp                                        *
 * Author:       Jan Kalina <xkalinj00>                                        *
 *                                                                             *
 * Created:      23.09.2025                                                    *
 * Last edit:    25.09.2025                                                    *
 *                                                                             *
 * Description:  This file contains the definition of the `CommandLineOptions` *
 *               class, which is used for storing command line options for     *
 *               the Filtering DNS Resolver.                                   *
 *                                                                             *
 ******************************************************************************/
/**
 * @file CommandLineOptions.hpp
 * @author Jan Kalina \<xkalinj00>
 * @brief Header file declaring the `CommandLineOptions` class.
 */

#ifndef COMMAND_LINE_OPTIONS_HPP
#define COMMAND_LINE_OPTIONS_HPP

#include "Constants/DefaultOptions.hpp"
#include <string>   // std::string
#include <cstdint>  // uint8_t, uint16_t

namespace FilteringDNSResolver::Arguments
{
    /**
     * @class CommandLineOptions
     * @brief A class for holding command line options for the Filtering DNS
     *        Resolver.
     */
    class CommandLineOptions final {
    public:
        std::string mResolverHostname;                                            /**< Server IP address or hostname.       */
        uint16_t mListenPort{Constants::DefaultOptions::DEFAULT_LISTENER_PORT};   /**< Server port number.                  */
        std::string mFilterFilePath;                                            /**< File containing the unwated domains. */
        bool mVerbose{false};                                                   /**< Verbose mode flag.                   */

        /**
         * @brief Equality operator for CommandLineOptions class.
         *
         * @details This operator compares two CommandLineOptions objects for
         *          equality. It is automatically generated by the compiler
         *          and compares all member variables.
         *
         * @param other The other CommandLineOptions object to compare with.
         * @return `true` if all member variables are equal, `false` otherwise.
         */
        bool operator==(const CommandLineOptions &other) const = default;
    }; // CommandLineOptions
} // FilteringDNSResolver::Arguments

#endif // COMMAND_LINE_OPTIONS_HPP

/*** end of file CommandLineOptions.hpp ***/
